export const UPDATE_POSTS = 'UPDATE_POSTS';

//login

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOGOUT = 'LOGOUT';
//Signup

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const CLEARAUTHSTATE = 'CLEARAUTHSTATE';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const FETCH_USER_PROFILE_START = 'FETCH_USER_PROFILE_START';

export const FETCH_USER_FRIENDS_SUCCESS = 'FETCH_USER_FRIENDS_SUCCESS';

export const ADD_FRIEND = 'ADD_FRIEND';

export const REMOVE_FRIEND = 'REMOVE_FRIEND';

export const CREATE_POST = 'CREATE_POST';
export const ADD_COMMENT = 'ADD_COMMENT';

export const UPDATE_POST_LIKE = 'UPDATE_POST_LIKE';

//Seearch

export const FETCH_SEARCH_RESULTSSUCCESS = 'FETCH_SEARCH_RESULTSSUCCESS';
